### PR TITLE
Enumerables

### PR DESCRIPTION
**Pull request by Ade179**
@Ade179 and @JacintaNgwu  created :
In this project we learnt learn how to use a module inside a class and we used it to create our enumerables

- A fun excercise

### CODE REVIEW

**Review by codecaiine — COMMENTED** [review]
Hi @Ade179 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has **Linters errors** and **incomplete readme file** . 
#### For your readme
- All main headers from the README template should be present. Even if there's no information for a section or sub-section, rather leave texts like "NA", "None" or "coming soon" than delete it. 
- Future Features section should include 1-3 potential features to be added. 
- Each section description should be removed and replaced with their custom content. The section descriptions are meant to guide you in documenting your README. They are not meant to be part of the final documentation. 
- The License suggestion should be removed. 
- There should not be any blank sections that do not have content. 
- There should not be any broken links in the README file. 
- Delete the live demo section if the application is not deployed. If project requirements say to deploy the project, the section should be restored and the link updated. 
- The template logo should be removed. Optionally, the Microverse logo can be replaced with your own project logo if you have one. 
- The only optional section is the FAQ section. If there's no information in the FAQ section then it should be deleted. 
- However, since you deleted the FAQ section, it would be best if you also removed it from the table of contents.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DammyShittu** [comment]
Hi @Ade179 and @JacintaNgwu,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly ensure your documentation is well-updated and there are no dummy sections. Kindly update these sections with relevant information instead of just leaving them blank. 

jjdie
urieew

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Qoosim — COMMENTED** [review]
#  *Status: Invalid Request* :red_circle: 

Hi @Ade179, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that 

- [ ] has conflict that needs to be resolved. Kindly resolve the confict and ask for review again

conflict


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢 🟢 🟢

Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gityflow correctly
✅ Linter checks passed 
✅ Implement Enumerable class methods as expected 👍🏽
✅ All test cases passed 👍🏽
✅ Good job working on the changes highlighted by the previous reviewers 👍🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
